server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://@localhost:3306/daily_life_logs_base?characterEncoding=utf8&useSSL=false&useAffectedRows=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: rootu
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*/*.xml


